name: Deploy

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, 'chore-')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_release_version: ${{ steps.tag.outputs.new_release_version }}
      previous_release_version: ${{ steps.previous_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Save Previous Tag
        id: previous_tag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Semantic Release
        if: github.event.head_commit.message != 'chore-${{ steps.previous_tag.outputs.tag }}'
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Store New Tag
        if: steps.semantic.outputs.new_release_published == 'true'
        id: tag
        run: |
          echo 'new_release_version=${{steps.semantic.outputs.new_release_version}}' >> $GITHUB_OUTPUT


  docker:
    if: "!contains(github.event.head_commit.message, 'chore-')"
    needs: [semantic-release]
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        id: build
        run: |
          echo ${{ needs.semantic-release.outputs.new_release_version }}
          echo "${{ needs.semantic-release.outputs.new_release_version }}"
          docker build . --file Dockerfile --tag emcpheron/sprint-planner:${{ needs.semantic-release.outputs.new_release_version }}

      - name: Tag the Docker image
        run: docker tag emcpheron/sprint-planner:${{ needs.semantic-release.outputs.new_release_version }} emcpheron/sprint-planner:${{ needs.semantic-release.outputs.new_release_version }}

      - name: Push the Docker image to Docker Hub
        run: docker push emcpheron/sprint-planner:${{ needs.semantic-release.outputs.new_release_version }}


  update-versions:
    if: "!contains(github.event.head_commit.message, 'chore-')"
    needs: [semantic-release, docker]
    name: Update Version Files
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: output
        run: |
          echo '${{toJSON(needs.semantic-release.outputs.new_release_version)}}'

      - name: Create branch
        run: |
          git checkout -b chore-${{ needs.semantic-release.outputs.previous_release_version }}

      - name: Update client file versions
        uses: jaywcjlove/github-action-package@main
        with:
          path: client/package.json
          data: |
            {
              "version": "${{ needs.semantic-release.outputs.new_release_version }}"
            }
      - name: Update server file versions
        uses: jaywcjlove/github-action-package@main
        with:
          path: server/package.json
          data: |
            {
              "version": "${{ needs.semantic-release.outputs.new_release_version }}"
            }

      - name: Update appVersion for helm
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'chart/Chart.yaml'
          propertyPath: 'appVersion'
          value: '${{ needs.semantic-release.outputs.new_release_version }}'
          masterBranchName: main
          targetBranch: main
          branch: chore-${{ needs.semantic-release.outputs.previous_tag }}
          message: 'chore-${{ needs.semantic-release.outputs.previous_tag }}'

      - name: Update version for helm
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'chart/Chart.yaml'
          propertyPath: 'version'
          value: '${{ needs.semantic-release.outputs.new_release_version }}'
          masterBranchName: main
          targetBranch: main
          branch: chore-${{ needs.semantic-release.outputs.new_release_version }}
          message: 'chore-${{ needs.semantic-release.outputs.new_release_version }}'

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git config pull.rebase true
          git add .
          git commit -m 'chore-${{ needs.semantic-release.outputs.new_release_version }}'
          git pull origin 'chore-${{ needs.semantic-release.outputs.new_release_version }}'
          git add .

      - name: Push changes
        if: github.event.head_commit.message != 'chore-${{ needs.semantic-release.outputs.new_release_version }}'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: 'chore-${{ needs.semantic-release.outputs.new_release_version }}'

      - name: Create PR
        id: pr
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.PAT }}
          commit-message: 'chore-${{ needs.semantic-release.outputs.new_release_version }}'
          title: 'chore-${{ needs.semantic-release.outputs.new_release_version }}'
          source_branch: 'chore-${{ needs.semantic-release.outputs.new_release_version }}'
          target_branch: main

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Pull Request Number - ${{ steps.pr.outputs.pr_number }}"
          echo "Pull Request URL - ${{ steps.pr.outputs.url }}"
          echo "Pull Request URL - ${{ toJSON(steps.pr.outputs) }}"
          echo ${{ github.event.pull_request.number }}
          gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ steps.pr.outputs.pr_number }}/merge \
          -f 'commit_title=chore-${{ needs.semantic-release.outputs.new_release_version }}' -f 'commit_message=chore-${{ needs.semantic-release.outputs.new_release_version }}'

      - name: Delete Branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.PAT}}
          numbers: ${{ steps.pr.outputs.pr_number }}
